FROM golang:latest

RUN go get -u -v github.com/go-sql-driver/mysql

RUN go get -u -v github.com/mongodb/mongo-go-driver/mongo

RUN go get -u -v github.com/julienschmidt/httprouter

RUN go get -u -v github.com/alecthomas/chroma/formatters/html

RUN go get -u -v github.com/alecthomas/chroma/lexers

RUN go get -u -v github.com/alecthomas/chroma/styles

RUN go get -u -v github.com/gomarkdown/markdown
