version: '3'
services:
  go:
    container_name: go-imaginative-go
    build: ./docker/golang
    volumes:
      - ./:/go/src/imaginative-go
    working_dir: /go/src/imaginative-go
    command: go run imaginative-go.go
    environment:
      - IGO_MONGODB_URI=mongodb://root:mongodbpassword@mongodb:27017
      - IGO_MONGODB_DATABASE=db-imaginative-go
      - IGO_ENV=prod
    ports:
      - "127.0.0.1:9899:9899"
    depends_on:
      - mongodb
    links:
      - mongodb
    #restart: always
    networks:
      - network-imaginative-go
  mongodb:
    container_name: mongodb-imaginative-go
    build: ./docker/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodbpassword
      MONGO_INITDB_DATABASE: db-imaginative-go
    networks:
      - network-imaginative-go
    restart: always
    volumes:
      - volume-mongodb-imaginative-go:/data/db
networks:
  network-imaginative-go:
volumes:
  volume-mongodb-imaginative-go: